# Generated by Django 4.1.5 on 2023-02-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('age', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/img')),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=30)),
                ('about', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'My_info',
                'verbose_name_plural': 'My infos',
            },
        ),
    ]
